### ISSUE TITLE
Create Icon UI (P)

### ISSUE THREAD

**Issue by pdkovacs** [ui-toolbox/icon-repository#39]
- [x] `addIcon` UI service #8 
- [x] UI control to start the "create icon" work-flow #11 
- [x] `IconFileAttributes` UI component #9
- [x] UI dialog for adding an icon #10
