### ISSUE TITLE
Add/remove icon file [P]

### ISSUE THREAD

**Issue by pdkovacs** [ui-toolbox/icon-repository#45]
- [x] Dialog to modify an icon #43
- [x] "removeIconFile" UI service #13
- [x] "addIconFile" UI service #12
