### ISSUE TITLE
Make starting the app locally in "near-production" configuration super-easy [P]

### ISSUE THREAD

**Issue by pdkovacs** [ui-toolbox/icon-repository#51]
The motivation is to extend testability and (eventually) initial content creation by non-dev personnel to environments where testing resources (dedicated test servers) are scarce.

The setup process shouldn't require more than
1. installing docker on the target machine and
1. executing a "copy-pastable" shell script
    (customized for the task which the setup is going to be used for)

Tasks
- [x] Clean-up packaging logic #52
- [x] Allow to configure a simple custom credentials store to be used with basic authentication #53
- [x] Clean-up and eventually extend the existing docker image configuration #54
- [x] Create a few (sample) (docker-compose) configuration files for the most common use cases #55

**Comment by pdkovacs** [comment]
Implemented in #79
